### ISSUE TITLE
Stepper Motor Library Support

### ISSUE THREAD

**Issue by FineLineAutomation** [MrYsLab/PyMata#1]
Do you support the stepper motor library of configurable firmata? If not, what would it take to implement it?

**Comment by jrr1984** [comment]
any updates here?

**Comment by MrYsLab** [comment]
Hi,
I am not sure what you are asking.
Are you asking if there are any updates with PyMata and Configurable Firmata? If that is your question, then the answer is no. I could never get Configurable Firmata to build and work, so I will not be supporting Configurable Firmata. If this is not your question, please explain.

**Comment by Manish2208** [comment]
How to control or connect 2 or 3 stepper motors using pymata with arduino?
Pls give some examples

**Comment by MrYsLab** [comment]
@Manish2208 Thanks for your question. The simple answer is that pymata can only support a single stepper motor. The reason for this is that the stepper motor library blocks when it is moving a motor. This then blocks the Firmata sketch. What this means, is that if you need to start a second motor while the first is running, you will not be able to until the stepper library is finished with the first motor. In addition, if you need to have real-time monitoring of a sensor while the stepper library is executing, because of the blocking, the sensor data update is blocked as well.

Also, I have not found an Arduino stepper motor board that can control more than a single stepper. One solution is to use i2c based motor controllers, such as the one from [Pololu](https://www.pololu.com/product/3131/blog). This is a very expensive solution, and you would be responsible to create the i2c code. This may or may not work with PyMata.

Please let me know if you have any other questions.
